on:
  push:
    branches:
    - main
    paths:
    - adf/**

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 18.x
        
    - name: install ADF Utilities package
      run: npm install
      working-directory: ${{github.workspace}}/adf/build  
        

    - name: Validate
      run: npm run build validate ${{github.workspace}}/adf /subscriptions/0b20b9d7-36c2-4bfe-b032-85a274f0e38e/resourceGroups/myresourcegroup/providers/Microsoft.DataFactory/factories/adf-salesdata2025 
      working-directory: ${{github.workspace}}/adf/build
 

    - name: Validate and Generate ARM template
      run: npm run build export ${{github.workspace}}/adf /subscriptions/0b20b9d7-36c2-4bfe-b032-85a274f0e38e/resourceGroups/myresourcegroup/providers/Microsoft.DataFactory/factories/adf-salesdata2025 "ExportedArmTemplate" 
      working-directory: ${{github.workspace}}/adf/build
 

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExportedArmTemplate 
        path: ${{github.workspace}}/adf/build/ExportedArmTemplate

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
  
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ExportedArmTemplate 


      - name: Login via Az module
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          enable-AzPSSession: true 

      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: newresource
          dataFactoryName: adf-salesdata2025-pr
          armTemplateFile: ARMTemplateForFactory.json
          armTemplateParametersFile: ARMTemplateParametersForFactory.json
   
